
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin 'spywhere/tmux-named-snapshot'
run "~/.tools/tpm/tpm"


unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-a
set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key x kill-pane

set -g base-index 1

darkgray="#24283b"
gray="#565f89"
gray2="#9aa5ce"
lightgray="#a9b1d6"
lightgray2="#c0caf5"
magenta="#bb9af7"
skyblue="#7aa2f7"
lightblue="#7dcfff"
cyan="#2ac3de"
iceblue="#b4f9f8"
green="#73dacb"
red="#f7768e"
orange="#ff9e64"

# Topbar Theme
set -g status-position top
set -g renumber-windows on
set -g status-left-length 100
set -g status-style fg=$gray2,bg=$darkgray
set -g window-status-separator ""
set -g status-left "#[fg=$gray,bg=$magenta,bold] #S #{?client_prefix,#[fg=$green]}#[fg=$magenta,bg=$darkgray]"
set -g window-status-format "#[fg=$skyblue,bg=$darkgray]#[bg=$skyblue,fg=$gray]#I #W #[fg=$skyblue,bg=$darkgray]" 
set -g window-status-current-format "#[fg=$gray,bg=$darkgray]#[bg=$gray,fg=$green,bold]#I #W #[fg=$gray,bg=$darkgray]"
set -g status-right "#[fg=$orange,bg=$darkgray] #[bg=$orange,fg=$gray,bold]%H.%M.%S #[fg=$orange,bg=$darkgray]#[fg=$red,bg=$darkgray]#[fg=$darkgray,bg=$red,bold]#h "
set -g status-interval 1

