
background #1a1b26
foreground  #c0caf5
background_opacity 0.9 
font_family JetBrainsMono Nerd Font
font_size 12

tab_bar_edge top


color0 #414868
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #7dcfff
color7 #a9b1d6
color8 #565f89
color9 #ff9aac
color10 #b5e879
color11 #ffd57a
color12 #a8c5ff
color13 #d4b8ff
color14 #a8eeff
color15 #c0caf5
